title: Kyuu Gallery
subtitle: Life is a moment.
description: 拿起相机，认真思考
cover: 'https://github.com/lfkdsk/picx-images-hosting/raw/master/20230817/IMG_7586.4e91my1ve140.17iz0sa56gik.webp'
author: kyuu

footer_logo: 
  use: self
  self:
    link: 'https:/aven9.github.io/'
    src: 'https://github.com/lfkdsk/picx-images-hosting/raw/master/20230817/tripper2white.2pbuwaqvndu0.webp'

url: https://aven9.github.io/kyuu-gallery
root: /kyuu-gallery

photography_page:
  slogan: true
  slogan_descr: 'The moments when I pressed the shutter, the moments are forever.'

# google_analytics: 
#   use: gtag
#   ga_id: 
#   ga_api: 
#   gtag_id: XXXXX

nav:
  归档: 
    link: https://aven9.github.io
    icon: inbox
  地图:
    link: /gallery/location
    icon: aiming
    
thumbnail_url: https://cdn.jsdelivr.net/gh/Aven9/kyuu-gallery@thumbnail/
base_url: https://cdn.jsdelivr.net/gh/Aven9/kyuu-gallery@master
