name: run build.py

on:
  workflow_dispatch:

env:
  GIT_USER: lfkdsk # change to yourself
  GIT_EMAIL: lfkdsk@gmail.com # change to yourself

jobs:
  build:
    runs-on: ubuntu-latest
    environment: secrets
    steps:
    - name: Deploy Thumbnail
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: .
        publish_branch: thumbnail
        github_token: ${{ secrets.GH_PAGES_DEPLOY }}
        user_name: ${{ env.GIT_USER }}
        user_email: ${{ env.GIT_EMAIL }}
        commit_msg: ${{ github.event.head_commit.message }}          